- hosts: all
  connection: network_cli
  become: yes
  become_method: enable
  tasks:
   - name: show version
     ios_command:
      commands: show version
     register: mm
   - debug: 
      var: mm.stdout
